export * from "./contact.controller";
export * from "./user.controller";
export * from "./virus-count.controller"
export * from "./district.controller";
export * from "./hospital.controller";
export * from "./nepal-count.controller";
export * from "./global-count.controller";
export * from "./news.controller";
export * from "./frontline.controller";